<div class="DiscoveryRingArea">
  <a id="DiscoveryRingLoadWidget" class="iframe" href="http://www.poesie.com.br/aro-de-anel/" title="Aneleira Virtual | Meça Aros de Anéis de Noivado, Alianças e Anéis">
    <img src="<?php echo $plugin_url_img; ?>" width="100%" alt="Descubra o tamanho do seu anel" />
  </a>
  <a target="_blank" class="DiscoveryRingLoadWidgetAssinatura" href="http://www.poesie.com.br" title="Aneleira Virtual | Meça Aros de Anéis de Noivado, Alianças e Anéis" >Poésie</a>
</div>
